// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConfigSrvCommon.proto

package io.panshi.config.srv;

public interface CommonRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.panshi.config.CommonResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.io.panshi.config.ErrCode code = 1;</code>
   */
  int getCodeValue();
  /**
   * <code>.io.panshi.config.ErrCode code = 1;</code>
   */
  io.panshi.config.srv.ErrCode getCode();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>string requestId = 3;</code>
   */
  java.lang.String getRequestId();
  /**
   * <code>string requestId = 3;</code>
   */
  com.google.protobuf.ByteString
      getRequestIdBytes();
}
