// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConfigSrvCommon.proto

package io.panshi.config.srv;

public final class Common {
  private Common() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_panshi_config_srv_CommonResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_panshi_config_srv_CommonResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Common.proto\022\024io.panshi.config.srv\"]\n\n" +
      "CommonResp\022+\n\004code\030\001 \001(\0162\035.io.panshi.con" +
      "fig.srv.ErrCode\022\017\n\007message\030\002 \001(\t\022\021\n\trequ" +
      "estId\030\003 \001(\t*\034\n\007ErrCode\022\021\n\rINVALID_INPUT\020" +
      "\000B\030\n\024io.panshi.config.srvP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_io_panshi_config_srv_CommonResp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_panshi_config_srv_CommonResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_panshi_config_srv_CommonResp_descriptor,
        new java.lang.String[] { "Code", "Message", "RequestId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
