// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConfigSrvDto.proto

package io.panshi.config.srv;

public interface ConfigDtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.panshi.config.srv.ConfigDto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string group = 1;</code>
   */
  java.lang.String getGroup();
  /**
   * <code>string group = 1;</code>
   */
  com.google.protobuf.ByteString
      getGroupBytes();

  /**
   * <code>string set = 2;</code>
   */
  java.lang.String getSet();
  /**
   * <code>string set = 2;</code>
   */
  com.google.protobuf.ByteString
      getSetBytes();

  /**
   * <code>string key = 3;</code>
   */
  java.lang.String getKey();
  /**
   * <code>string key = 3;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>string configValueType = 4;</code>
   */
  java.lang.String getConfigValueType();
  /**
   * <code>string configValueType = 4;</code>
   */
  com.google.protobuf.ByteString
      getConfigValueTypeBytes();

  /**
   * <code>string content = 5;</code>
   */
  java.lang.String getContent();
  /**
   * <code>string content = 5;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>int64 version = 6;</code>
   */
  long getVersion();
}
