// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConfigSrv.proto

package io.panshi.config.srv;

public final class ConfigSrvOuterClass {
  private ConfigSrvOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017ConfigSrv.proto\022\024io.panshi.config.srv\032" +
      "\022ConfigSrvDto.proto2\353\001\n\tConfigSrv\022e\n\014cre" +
      "ateConfig\022).io.panshi.config.srv.CreateC" +
      "onfigRequest\032*.io.panshi.config.srv.Crea" +
      "teConfigResponse\022w\n\022describeConfigList\022/" +
      ".io.panshi.config.srv.DescribeConfigList" +
      "Request\0320.io.panshi.config.srv.DescribeC" +
      "onfigListResponseB\030\n\024io.panshi.config.sr" +
      "vP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.panshi.config.srv.ConfigSrvDto.getDescriptor(),
        }, assigner);
    io.panshi.config.srv.ConfigSrvDto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
