// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConfigSrv.proto

package io.panshi.config.srv;

public final class ConfigSrvOuterClass {
  private ConfigSrvOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_panshi_config_srv_DescribeConfigDetailRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_panshi_config_srv_DescribeConfigDetailRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_panshi_config_srv_DescribeConfigDetailResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_panshi_config_srv_DescribeConfigDetailResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017ConfigSrv.proto\022\024io.panshi.config.srv\"" +
      "+\n\033DescribeConfigDetailRequest\022\014\n\004name\030\001" +
      " \001(\t\"0\n\034DescribeConfigDetailResponse\022\020\n\010" +
      "greeting\030\001 \001(\t2\212\001\n\tConfigSrv\022}\n\024describe" +
      "ConfigDetail\0221.io.panshi.config.srv.Desc" +
      "ribeConfigDetailRequest\0322.io.panshi.conf" +
      "ig.srv.DescribeConfigDetailResponseB\002P\001b" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_io_panshi_config_srv_DescribeConfigDetailRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_panshi_config_srv_DescribeConfigDetailRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_panshi_config_srv_DescribeConfigDetailRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_io_panshi_config_srv_DescribeConfigDetailResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_io_panshi_config_srv_DescribeConfigDetailResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_panshi_config_srv_DescribeConfigDetailResponse_descriptor,
        new java.lang.String[] { "Greeting", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
