// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConfigSrvDto.proto

package io.panshi.config.srv;

public final class ConfigSrvDto {
  private ConfigSrvDto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_panshi_config_srv_DescribeConfigDetailResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_panshi_config_srv_DescribeConfigDetailResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_panshi_config_srv_DescribeConfigDetailRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_panshi_config_srv_DescribeConfigDetailRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_panshi_config_srv_CreateConfigReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_panshi_config_srv_CreateConfigReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_panshi_config_srv_CreateConfigResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_panshi_config_srv_CreateConfigResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022ConfigSrvDto.proto\022\024io.panshi.config.s" +
      "rv\032\025ConfigSrvCommon.proto\"0\n\034DescribeCon" +
      "figDetailResponse\022\020\n\010greeting\030\001 \001(\t\"+\n\033D" +
      "escribeConfigDetailRequest\022\014\n\004name\030\001 \001(\t" +
      "\"`\n\017CreateConfigReq\022\013\n\003key\030\001 \001(\t\022\r\n\005grou" +
      "p\030\002 \001(\t\022\013\n\003set\030\003 \001(\t\022\017\n\007content\030\004 \001(\t\022\023\n" +
      "\013contentType\030\005 \001(\t\"N\n\020CreateConfigResp\022." +
      "\n\004cRsp\030\001 \001(\0132 .io.panshi.config.srv.Comm" +
      "onResp\022\n\n\002id\030\002 \001(\tB\030\n\024io.panshi.config.s" +
      "rvP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.panshi.config.srv.ConfigSrvCommon.getDescriptor(),
        }, assigner);
    internal_static_io_panshi_config_srv_DescribeConfigDetailResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_panshi_config_srv_DescribeConfigDetailResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_panshi_config_srv_DescribeConfigDetailResponse_descriptor,
        new java.lang.String[] { "Greeting", });
    internal_static_io_panshi_config_srv_DescribeConfigDetailRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_io_panshi_config_srv_DescribeConfigDetailRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_panshi_config_srv_DescribeConfigDetailRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_io_panshi_config_srv_CreateConfigReq_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_io_panshi_config_srv_CreateConfigReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_panshi_config_srv_CreateConfigReq_descriptor,
        new java.lang.String[] { "Key", "Group", "Set", "Content", "ContentType", });
    internal_static_io_panshi_config_srv_CreateConfigResp_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_io_panshi_config_srv_CreateConfigResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_panshi_config_srv_CreateConfigResp_descriptor,
        new java.lang.String[] { "CRsp", "Id", });
    io.panshi.config.srv.ConfigSrvCommon.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
