// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConfigSrvDto.proto

package io.panshi.config.srv;

/**
 * Protobuf type {@code io.panshi.config.srv.CreateConfigResp}
 */
public  final class CreateConfigResp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:io.panshi.config.srv.CreateConfigResp)
    CreateConfigRespOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateConfigResp.newBuilder() to construct.
  private CreateConfigResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateConfigResp() {
    id_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CreateConfigResp(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            io.panshi.config.srv.CommonResp.Builder subBuilder = null;
            if (cRsp_ != null) {
              subBuilder = cRsp_.toBuilder();
            }
            cRsp_ = input.readMessage(io.panshi.config.srv.CommonResp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(cRsp_);
              cRsp_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.panshi.config.srv.ConfigSrvDto.internal_static_io_panshi_config_srv_CreateConfigResp_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.panshi.config.srv.ConfigSrvDto.internal_static_io_panshi_config_srv_CreateConfigResp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.panshi.config.srv.CreateConfigResp.class, io.panshi.config.srv.CreateConfigResp.Builder.class);
  }

  public static final int CRSP_FIELD_NUMBER = 1;
  private io.panshi.config.srv.CommonResp cRsp_;
  /**
   * <code>.io.panshi.config.srv.CommonResp cRsp = 1;</code>
   */
  public boolean hasCRsp() {
    return cRsp_ != null;
  }
  /**
   * <code>.io.panshi.config.srv.CommonResp cRsp = 1;</code>
   */
  public io.panshi.config.srv.CommonResp getCRsp() {
    return cRsp_ == null ? io.panshi.config.srv.CommonResp.getDefaultInstance() : cRsp_;
  }
  /**
   * <code>.io.panshi.config.srv.CommonResp cRsp = 1;</code>
   */
  public io.panshi.config.srv.CommonRespOrBuilder getCRspOrBuilder() {
    return getCRsp();
  }

  public static final int ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 2;</code>
   */
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 2;</code>
   */
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (cRsp_ != null) {
      output.writeMessage(1, getCRsp());
    }
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, id_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (cRsp_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getCRsp());
    }
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, id_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.panshi.config.srv.CreateConfigResp)) {
      return super.equals(obj);
    }
    io.panshi.config.srv.CreateConfigResp other = (io.panshi.config.srv.CreateConfigResp) obj;

    boolean result = true;
    result = result && (hasCRsp() == other.hasCRsp());
    if (hasCRsp()) {
      result = result && getCRsp()
          .equals(other.getCRsp());
    }
    result = result && getId()
        .equals(other.getId());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCRsp()) {
      hash = (37 * hash) + CRSP_FIELD_NUMBER;
      hash = (53 * hash) + getCRsp().hashCode();
    }
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.panshi.config.srv.CreateConfigResp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.panshi.config.srv.CreateConfigResp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.panshi.config.srv.CreateConfigResp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.panshi.config.srv.CreateConfigResp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.panshi.config.srv.CreateConfigResp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.panshi.config.srv.CreateConfigResp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.panshi.config.srv.CreateConfigResp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.panshi.config.srv.CreateConfigResp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.panshi.config.srv.CreateConfigResp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.panshi.config.srv.CreateConfigResp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.panshi.config.srv.CreateConfigResp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.panshi.config.srv.CreateConfigResp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.panshi.config.srv.CreateConfigResp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code io.panshi.config.srv.CreateConfigResp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.panshi.config.srv.CreateConfigResp)
      io.panshi.config.srv.CreateConfigRespOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.panshi.config.srv.ConfigSrvDto.internal_static_io_panshi_config_srv_CreateConfigResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.panshi.config.srv.ConfigSrvDto.internal_static_io_panshi_config_srv_CreateConfigResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.panshi.config.srv.CreateConfigResp.class, io.panshi.config.srv.CreateConfigResp.Builder.class);
    }

    // Construct using io.panshi.config.srv.CreateConfigResp.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (cRspBuilder_ == null) {
        cRsp_ = null;
      } else {
        cRsp_ = null;
        cRspBuilder_ = null;
      }
      id_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.panshi.config.srv.ConfigSrvDto.internal_static_io_panshi_config_srv_CreateConfigResp_descriptor;
    }

    @java.lang.Override
    public io.panshi.config.srv.CreateConfigResp getDefaultInstanceForType() {
      return io.panshi.config.srv.CreateConfigResp.getDefaultInstance();
    }

    @java.lang.Override
    public io.panshi.config.srv.CreateConfigResp build() {
      io.panshi.config.srv.CreateConfigResp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.panshi.config.srv.CreateConfigResp buildPartial() {
      io.panshi.config.srv.CreateConfigResp result = new io.panshi.config.srv.CreateConfigResp(this);
      if (cRspBuilder_ == null) {
        result.cRsp_ = cRsp_;
      } else {
        result.cRsp_ = cRspBuilder_.build();
      }
      result.id_ = id_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.panshi.config.srv.CreateConfigResp) {
        return mergeFrom((io.panshi.config.srv.CreateConfigResp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.panshi.config.srv.CreateConfigResp other) {
      if (other == io.panshi.config.srv.CreateConfigResp.getDefaultInstance()) return this;
      if (other.hasCRsp()) {
        mergeCRsp(other.getCRsp());
      }
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.panshi.config.srv.CreateConfigResp parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.panshi.config.srv.CreateConfigResp) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private io.panshi.config.srv.CommonResp cRsp_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.panshi.config.srv.CommonResp, io.panshi.config.srv.CommonResp.Builder, io.panshi.config.srv.CommonRespOrBuilder> cRspBuilder_;
    /**
     * <code>.io.panshi.config.srv.CommonResp cRsp = 1;</code>
     */
    public boolean hasCRsp() {
      return cRspBuilder_ != null || cRsp_ != null;
    }
    /**
     * <code>.io.panshi.config.srv.CommonResp cRsp = 1;</code>
     */
    public io.panshi.config.srv.CommonResp getCRsp() {
      if (cRspBuilder_ == null) {
        return cRsp_ == null ? io.panshi.config.srv.CommonResp.getDefaultInstance() : cRsp_;
      } else {
        return cRspBuilder_.getMessage();
      }
    }
    /**
     * <code>.io.panshi.config.srv.CommonResp cRsp = 1;</code>
     */
    public Builder setCRsp(io.panshi.config.srv.CommonResp value) {
      if (cRspBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        cRsp_ = value;
        onChanged();
      } else {
        cRspBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.io.panshi.config.srv.CommonResp cRsp = 1;</code>
     */
    public Builder setCRsp(
        io.panshi.config.srv.CommonResp.Builder builderForValue) {
      if (cRspBuilder_ == null) {
        cRsp_ = builderForValue.build();
        onChanged();
      } else {
        cRspBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.io.panshi.config.srv.CommonResp cRsp = 1;</code>
     */
    public Builder mergeCRsp(io.panshi.config.srv.CommonResp value) {
      if (cRspBuilder_ == null) {
        if (cRsp_ != null) {
          cRsp_ =
            io.panshi.config.srv.CommonResp.newBuilder(cRsp_).mergeFrom(value).buildPartial();
        } else {
          cRsp_ = value;
        }
        onChanged();
      } else {
        cRspBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.io.panshi.config.srv.CommonResp cRsp = 1;</code>
     */
    public Builder clearCRsp() {
      if (cRspBuilder_ == null) {
        cRsp_ = null;
        onChanged();
      } else {
        cRsp_ = null;
        cRspBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.io.panshi.config.srv.CommonResp cRsp = 1;</code>
     */
    public io.panshi.config.srv.CommonResp.Builder getCRspBuilder() {
      
      onChanged();
      return getCRspFieldBuilder().getBuilder();
    }
    /**
     * <code>.io.panshi.config.srv.CommonResp cRsp = 1;</code>
     */
    public io.panshi.config.srv.CommonRespOrBuilder getCRspOrBuilder() {
      if (cRspBuilder_ != null) {
        return cRspBuilder_.getMessageOrBuilder();
      } else {
        return cRsp_ == null ?
            io.panshi.config.srv.CommonResp.getDefaultInstance() : cRsp_;
      }
    }
    /**
     * <code>.io.panshi.config.srv.CommonResp cRsp = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.panshi.config.srv.CommonResp, io.panshi.config.srv.CommonResp.Builder, io.panshi.config.srv.CommonRespOrBuilder> 
        getCRspFieldBuilder() {
      if (cRspBuilder_ == null) {
        cRspBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.panshi.config.srv.CommonResp, io.panshi.config.srv.CommonResp.Builder, io.panshi.config.srv.CommonRespOrBuilder>(
                getCRsp(),
                getParentForChildren(),
                isClean());
        cRsp_ = null;
      }
      return cRspBuilder_;
    }

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 2;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 2;</code>
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 2;</code>
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 2;</code>
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:io.panshi.config.srv.CreateConfigResp)
  }

  // @@protoc_insertion_point(class_scope:io.panshi.config.srv.CreateConfigResp)
  private static final io.panshi.config.srv.CreateConfigResp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.panshi.config.srv.CreateConfigResp();
  }

  public static io.panshi.config.srv.CreateConfigResp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateConfigResp>
      PARSER = new com.google.protobuf.AbstractParser<CreateConfigResp>() {
    @java.lang.Override
    public CreateConfigResp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CreateConfigResp(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CreateConfigResp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateConfigResp> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.panshi.config.srv.CreateConfigResp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

