// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConfigSrvDto.proto

package io.panshi.config.srv;

public interface CreateConfigRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.panshi.config.CreateConfigRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string key = 1;</code>
   */
  java.lang.String getKey();
  /**
   * <code>string key = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>string group = 2;</code>
   */
  java.lang.String getGroup();
  /**
   * <code>string group = 2;</code>
   */
  com.google.protobuf.ByteString
      getGroupBytes();

  /**
   * <code>string set = 3;</code>
   */
  java.lang.String getSet();
  /**
   * <code>string set = 3;</code>
   */
  com.google.protobuf.ByteString
      getSetBytes();

  /**
   * <code>string content = 4;</code>
   */
  java.lang.String getContent();
  /**
   * <code>string content = 4;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>string contentType = 5;</code>
   */
  java.lang.String getContentType();
  /**
   * <code>string contentType = 5;</code>
   */
  com.google.protobuf.ByteString
      getContentTypeBytes();
}
