// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConfigSrv.proto

package io.panshi.config.srv;

public interface DescribeConfigDetailRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.panshi.config.srv.DescribeConfigDetailRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
