// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConfigSrvDto.proto

package io.panshi.config.srv;

public interface DescribeConfigListRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.panshi.config.srv.DescribeConfigListRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string filterKeyword = 1;</code>
   */
  java.lang.String getFilterKeyword();
  /**
   * <code>string filterKeyword = 1;</code>
   */
  com.google.protobuf.ByteString
      getFilterKeywordBytes();
}
