// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConfigSrvCommon.proto

package io.panshi.config.srv;

/**
 * Protobuf enum {@code io.panshi.config.srv.ErrCode}
 */
public enum ErrCode
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>INVALID_INPUT = 0;</code>
   */
  INVALID_INPUT(0),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>INVALID_INPUT = 0;</code>
   */
  public static final int INVALID_INPUT_VALUE = 0;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ErrCode valueOf(int value) {
    return forNumber(value);
  }

  public static ErrCode forNumber(int value) {
    switch (value) {
      case 0: return INVALID_INPUT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ErrCode>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ErrCode> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ErrCode>() {
          public ErrCode findValueByNumber(int number) {
            return ErrCode.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return io.panshi.config.srv.ConfigSrvCommon.getDescriptor().getEnumTypes().get(0);
  }

  private static final ErrCode[] VALUES = values();

  public static ErrCode valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ErrCode(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:io.panshi.config.srv.ErrCode)
}

