// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConfigSrvDto.proto

package io.panshi.config.srv;

/**
 * Protobuf type {@code io.panshi.config.PullConfigListResponse}
 */
public  final class PullConfigListResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:io.panshi.config.PullConfigListResponse)
    PullConfigListResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PullConfigListResponse.newBuilder() to construct.
  private PullConfigListResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PullConfigListResponse() {
    lastVersion_ = 0L;
    configList_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PullConfigListResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            io.panshi.config.srv.CommonResp.Builder subBuilder = null;
            if (cRsp_ != null) {
              subBuilder = cRsp_.toBuilder();
            }
            cRsp_ = input.readMessage(io.panshi.config.srv.CommonResp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(cRsp_);
              cRsp_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {

            lastVersion_ = input.readInt64();
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              configList_ = new java.util.ArrayList<io.panshi.config.srv.ConfigDto>();
              mutable_bitField0_ |= 0x00000004;
            }
            configList_.add(
                input.readMessage(io.panshi.config.srv.ConfigDto.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        configList_ = java.util.Collections.unmodifiableList(configList_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.panshi.config.srv.ConfigSrvDto.internal_static_io_panshi_config_PullConfigListResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.panshi.config.srv.ConfigSrvDto.internal_static_io_panshi_config_PullConfigListResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.panshi.config.srv.PullConfigListResponse.class, io.panshi.config.srv.PullConfigListResponse.Builder.class);
  }

  private int bitField0_;
  public static final int CRSP_FIELD_NUMBER = 1;
  private io.panshi.config.srv.CommonResp cRsp_;
  /**
   * <code>.io.panshi.config.CommonResp cRsp = 1;</code>
   */
  public boolean hasCRsp() {
    return cRsp_ != null;
  }
  /**
   * <code>.io.panshi.config.CommonResp cRsp = 1;</code>
   */
  public io.panshi.config.srv.CommonResp getCRsp() {
    return cRsp_ == null ? io.panshi.config.srv.CommonResp.getDefaultInstance() : cRsp_;
  }
  /**
   * <code>.io.panshi.config.CommonResp cRsp = 1;</code>
   */
  public io.panshi.config.srv.CommonRespOrBuilder getCRspOrBuilder() {
    return getCRsp();
  }

  public static final int LASTVERSION_FIELD_NUMBER = 2;
  private long lastVersion_;
  /**
   * <code>int64 lastVersion = 2;</code>
   */
  public long getLastVersion() {
    return lastVersion_;
  }

  public static final int CONFIGLIST_FIELD_NUMBER = 3;
  private java.util.List<io.panshi.config.srv.ConfigDto> configList_;
  /**
   * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
   */
  public java.util.List<io.panshi.config.srv.ConfigDto> getConfigListList() {
    return configList_;
  }
  /**
   * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
   */
  public java.util.List<? extends io.panshi.config.srv.ConfigDtoOrBuilder> 
      getConfigListOrBuilderList() {
    return configList_;
  }
  /**
   * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
   */
  public int getConfigListCount() {
    return configList_.size();
  }
  /**
   * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
   */
  public io.panshi.config.srv.ConfigDto getConfigList(int index) {
    return configList_.get(index);
  }
  /**
   * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
   */
  public io.panshi.config.srv.ConfigDtoOrBuilder getConfigListOrBuilder(
      int index) {
    return configList_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (cRsp_ != null) {
      output.writeMessage(1, getCRsp());
    }
    if (lastVersion_ != 0L) {
      output.writeInt64(2, lastVersion_);
    }
    for (int i = 0; i < configList_.size(); i++) {
      output.writeMessage(3, configList_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (cRsp_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getCRsp());
    }
    if (lastVersion_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, lastVersion_);
    }
    for (int i = 0; i < configList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, configList_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.panshi.config.srv.PullConfigListResponse)) {
      return super.equals(obj);
    }
    io.panshi.config.srv.PullConfigListResponse other = (io.panshi.config.srv.PullConfigListResponse) obj;

    boolean result = true;
    result = result && (hasCRsp() == other.hasCRsp());
    if (hasCRsp()) {
      result = result && getCRsp()
          .equals(other.getCRsp());
    }
    result = result && (getLastVersion()
        == other.getLastVersion());
    result = result && getConfigListList()
        .equals(other.getConfigListList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCRsp()) {
      hash = (37 * hash) + CRSP_FIELD_NUMBER;
      hash = (53 * hash) + getCRsp().hashCode();
    }
    hash = (37 * hash) + LASTVERSION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLastVersion());
    if (getConfigListCount() > 0) {
      hash = (37 * hash) + CONFIGLIST_FIELD_NUMBER;
      hash = (53 * hash) + getConfigListList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.panshi.config.srv.PullConfigListResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.panshi.config.srv.PullConfigListResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.panshi.config.srv.PullConfigListResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.panshi.config.srv.PullConfigListResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.panshi.config.srv.PullConfigListResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.panshi.config.srv.PullConfigListResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.panshi.config.srv.PullConfigListResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.panshi.config.srv.PullConfigListResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.panshi.config.srv.PullConfigListResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.panshi.config.srv.PullConfigListResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.panshi.config.srv.PullConfigListResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.panshi.config.srv.PullConfigListResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.panshi.config.srv.PullConfigListResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code io.panshi.config.PullConfigListResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.panshi.config.PullConfigListResponse)
      io.panshi.config.srv.PullConfigListResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.panshi.config.srv.ConfigSrvDto.internal_static_io_panshi_config_PullConfigListResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.panshi.config.srv.ConfigSrvDto.internal_static_io_panshi_config_PullConfigListResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.panshi.config.srv.PullConfigListResponse.class, io.panshi.config.srv.PullConfigListResponse.Builder.class);
    }

    // Construct using io.panshi.config.srv.PullConfigListResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getConfigListFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (cRspBuilder_ == null) {
        cRsp_ = null;
      } else {
        cRsp_ = null;
        cRspBuilder_ = null;
      }
      lastVersion_ = 0L;

      if (configListBuilder_ == null) {
        configList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        configListBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.panshi.config.srv.ConfigSrvDto.internal_static_io_panshi_config_PullConfigListResponse_descriptor;
    }

    @java.lang.Override
    public io.panshi.config.srv.PullConfigListResponse getDefaultInstanceForType() {
      return io.panshi.config.srv.PullConfigListResponse.getDefaultInstance();
    }

    @java.lang.Override
    public io.panshi.config.srv.PullConfigListResponse build() {
      io.panshi.config.srv.PullConfigListResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.panshi.config.srv.PullConfigListResponse buildPartial() {
      io.panshi.config.srv.PullConfigListResponse result = new io.panshi.config.srv.PullConfigListResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (cRspBuilder_ == null) {
        result.cRsp_ = cRsp_;
      } else {
        result.cRsp_ = cRspBuilder_.build();
      }
      result.lastVersion_ = lastVersion_;
      if (configListBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          configList_ = java.util.Collections.unmodifiableList(configList_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.configList_ = configList_;
      } else {
        result.configList_ = configListBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.panshi.config.srv.PullConfigListResponse) {
        return mergeFrom((io.panshi.config.srv.PullConfigListResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.panshi.config.srv.PullConfigListResponse other) {
      if (other == io.panshi.config.srv.PullConfigListResponse.getDefaultInstance()) return this;
      if (other.hasCRsp()) {
        mergeCRsp(other.getCRsp());
      }
      if (other.getLastVersion() != 0L) {
        setLastVersion(other.getLastVersion());
      }
      if (configListBuilder_ == null) {
        if (!other.configList_.isEmpty()) {
          if (configList_.isEmpty()) {
            configList_ = other.configList_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureConfigListIsMutable();
            configList_.addAll(other.configList_);
          }
          onChanged();
        }
      } else {
        if (!other.configList_.isEmpty()) {
          if (configListBuilder_.isEmpty()) {
            configListBuilder_.dispose();
            configListBuilder_ = null;
            configList_ = other.configList_;
            bitField0_ = (bitField0_ & ~0x00000004);
            configListBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getConfigListFieldBuilder() : null;
          } else {
            configListBuilder_.addAllMessages(other.configList_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.panshi.config.srv.PullConfigListResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.panshi.config.srv.PullConfigListResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private io.panshi.config.srv.CommonResp cRsp_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.panshi.config.srv.CommonResp, io.panshi.config.srv.CommonResp.Builder, io.panshi.config.srv.CommonRespOrBuilder> cRspBuilder_;
    /**
     * <code>.io.panshi.config.CommonResp cRsp = 1;</code>
     */
    public boolean hasCRsp() {
      return cRspBuilder_ != null || cRsp_ != null;
    }
    /**
     * <code>.io.panshi.config.CommonResp cRsp = 1;</code>
     */
    public io.panshi.config.srv.CommonResp getCRsp() {
      if (cRspBuilder_ == null) {
        return cRsp_ == null ? io.panshi.config.srv.CommonResp.getDefaultInstance() : cRsp_;
      } else {
        return cRspBuilder_.getMessage();
      }
    }
    /**
     * <code>.io.panshi.config.CommonResp cRsp = 1;</code>
     */
    public Builder setCRsp(io.panshi.config.srv.CommonResp value) {
      if (cRspBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        cRsp_ = value;
        onChanged();
      } else {
        cRspBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.io.panshi.config.CommonResp cRsp = 1;</code>
     */
    public Builder setCRsp(
        io.panshi.config.srv.CommonResp.Builder builderForValue) {
      if (cRspBuilder_ == null) {
        cRsp_ = builderForValue.build();
        onChanged();
      } else {
        cRspBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.io.panshi.config.CommonResp cRsp = 1;</code>
     */
    public Builder mergeCRsp(io.panshi.config.srv.CommonResp value) {
      if (cRspBuilder_ == null) {
        if (cRsp_ != null) {
          cRsp_ =
            io.panshi.config.srv.CommonResp.newBuilder(cRsp_).mergeFrom(value).buildPartial();
        } else {
          cRsp_ = value;
        }
        onChanged();
      } else {
        cRspBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.io.panshi.config.CommonResp cRsp = 1;</code>
     */
    public Builder clearCRsp() {
      if (cRspBuilder_ == null) {
        cRsp_ = null;
        onChanged();
      } else {
        cRsp_ = null;
        cRspBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.io.panshi.config.CommonResp cRsp = 1;</code>
     */
    public io.panshi.config.srv.CommonResp.Builder getCRspBuilder() {
      
      onChanged();
      return getCRspFieldBuilder().getBuilder();
    }
    /**
     * <code>.io.panshi.config.CommonResp cRsp = 1;</code>
     */
    public io.panshi.config.srv.CommonRespOrBuilder getCRspOrBuilder() {
      if (cRspBuilder_ != null) {
        return cRspBuilder_.getMessageOrBuilder();
      } else {
        return cRsp_ == null ?
            io.panshi.config.srv.CommonResp.getDefaultInstance() : cRsp_;
      }
    }
    /**
     * <code>.io.panshi.config.CommonResp cRsp = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.panshi.config.srv.CommonResp, io.panshi.config.srv.CommonResp.Builder, io.panshi.config.srv.CommonRespOrBuilder> 
        getCRspFieldBuilder() {
      if (cRspBuilder_ == null) {
        cRspBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.panshi.config.srv.CommonResp, io.panshi.config.srv.CommonResp.Builder, io.panshi.config.srv.CommonRespOrBuilder>(
                getCRsp(),
                getParentForChildren(),
                isClean());
        cRsp_ = null;
      }
      return cRspBuilder_;
    }

    private long lastVersion_ ;
    /**
     * <code>int64 lastVersion = 2;</code>
     */
    public long getLastVersion() {
      return lastVersion_;
    }
    /**
     * <code>int64 lastVersion = 2;</code>
     */
    public Builder setLastVersion(long value) {
      
      lastVersion_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 lastVersion = 2;</code>
     */
    public Builder clearLastVersion() {
      
      lastVersion_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<io.panshi.config.srv.ConfigDto> configList_ =
      java.util.Collections.emptyList();
    private void ensureConfigListIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        configList_ = new java.util.ArrayList<io.panshi.config.srv.ConfigDto>(configList_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.panshi.config.srv.ConfigDto, io.panshi.config.srv.ConfigDto.Builder, io.panshi.config.srv.ConfigDtoOrBuilder> configListBuilder_;

    /**
     * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
     */
    public java.util.List<io.panshi.config.srv.ConfigDto> getConfigListList() {
      if (configListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(configList_);
      } else {
        return configListBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
     */
    public int getConfigListCount() {
      if (configListBuilder_ == null) {
        return configList_.size();
      } else {
        return configListBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
     */
    public io.panshi.config.srv.ConfigDto getConfigList(int index) {
      if (configListBuilder_ == null) {
        return configList_.get(index);
      } else {
        return configListBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
     */
    public Builder setConfigList(
        int index, io.panshi.config.srv.ConfigDto value) {
      if (configListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureConfigListIsMutable();
        configList_.set(index, value);
        onChanged();
      } else {
        configListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
     */
    public Builder setConfigList(
        int index, io.panshi.config.srv.ConfigDto.Builder builderForValue) {
      if (configListBuilder_ == null) {
        ensureConfigListIsMutable();
        configList_.set(index, builderForValue.build());
        onChanged();
      } else {
        configListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
     */
    public Builder addConfigList(io.panshi.config.srv.ConfigDto value) {
      if (configListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureConfigListIsMutable();
        configList_.add(value);
        onChanged();
      } else {
        configListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
     */
    public Builder addConfigList(
        int index, io.panshi.config.srv.ConfigDto value) {
      if (configListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureConfigListIsMutable();
        configList_.add(index, value);
        onChanged();
      } else {
        configListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
     */
    public Builder addConfigList(
        io.panshi.config.srv.ConfigDto.Builder builderForValue) {
      if (configListBuilder_ == null) {
        ensureConfigListIsMutable();
        configList_.add(builderForValue.build());
        onChanged();
      } else {
        configListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
     */
    public Builder addConfigList(
        int index, io.panshi.config.srv.ConfigDto.Builder builderForValue) {
      if (configListBuilder_ == null) {
        ensureConfigListIsMutable();
        configList_.add(index, builderForValue.build());
        onChanged();
      } else {
        configListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
     */
    public Builder addAllConfigList(
        java.lang.Iterable<? extends io.panshi.config.srv.ConfigDto> values) {
      if (configListBuilder_ == null) {
        ensureConfigListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, configList_);
        onChanged();
      } else {
        configListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
     */
    public Builder clearConfigList() {
      if (configListBuilder_ == null) {
        configList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        configListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
     */
    public Builder removeConfigList(int index) {
      if (configListBuilder_ == null) {
        ensureConfigListIsMutable();
        configList_.remove(index);
        onChanged();
      } else {
        configListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
     */
    public io.panshi.config.srv.ConfigDto.Builder getConfigListBuilder(
        int index) {
      return getConfigListFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
     */
    public io.panshi.config.srv.ConfigDtoOrBuilder getConfigListOrBuilder(
        int index) {
      if (configListBuilder_ == null) {
        return configList_.get(index);  } else {
        return configListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
     */
    public java.util.List<? extends io.panshi.config.srv.ConfigDtoOrBuilder> 
         getConfigListOrBuilderList() {
      if (configListBuilder_ != null) {
        return configListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(configList_);
      }
    }
    /**
     * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
     */
    public io.panshi.config.srv.ConfigDto.Builder addConfigListBuilder() {
      return getConfigListFieldBuilder().addBuilder(
          io.panshi.config.srv.ConfigDto.getDefaultInstance());
    }
    /**
     * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
     */
    public io.panshi.config.srv.ConfigDto.Builder addConfigListBuilder(
        int index) {
      return getConfigListFieldBuilder().addBuilder(
          index, io.panshi.config.srv.ConfigDto.getDefaultInstance());
    }
    /**
     * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
     */
    public java.util.List<io.panshi.config.srv.ConfigDto.Builder> 
         getConfigListBuilderList() {
      return getConfigListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.panshi.config.srv.ConfigDto, io.panshi.config.srv.ConfigDto.Builder, io.panshi.config.srv.ConfigDtoOrBuilder> 
        getConfigListFieldBuilder() {
      if (configListBuilder_ == null) {
        configListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.panshi.config.srv.ConfigDto, io.panshi.config.srv.ConfigDto.Builder, io.panshi.config.srv.ConfigDtoOrBuilder>(
                configList_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        configList_ = null;
      }
      return configListBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:io.panshi.config.PullConfigListResponse)
  }

  // @@protoc_insertion_point(class_scope:io.panshi.config.PullConfigListResponse)
  private static final io.panshi.config.srv.PullConfigListResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.panshi.config.srv.PullConfigListResponse();
  }

  public static io.panshi.config.srv.PullConfigListResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PullConfigListResponse>
      PARSER = new com.google.protobuf.AbstractParser<PullConfigListResponse>() {
    @java.lang.Override
    public PullConfigListResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PullConfigListResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PullConfigListResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PullConfigListResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.panshi.config.srv.PullConfigListResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

