// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConfigSrvDto.proto

package io.panshi.config.srv;

public interface PullConfigListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.panshi.config.PullConfigListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.io.panshi.config.CommonResp cRsp = 1;</code>
   */
  boolean hasCRsp();
  /**
   * <code>.io.panshi.config.CommonResp cRsp = 1;</code>
   */
  io.panshi.config.srv.CommonResp getCRsp();
  /**
   * <code>.io.panshi.config.CommonResp cRsp = 1;</code>
   */
  io.panshi.config.srv.CommonRespOrBuilder getCRspOrBuilder();

  /**
   * <code>int64 lastVersion = 2;</code>
   */
  long getLastVersion();

  /**
   * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
   */
  java.util.List<io.panshi.config.srv.ConfigDto> 
      getConfigListList();
  /**
   * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
   */
  io.panshi.config.srv.ConfigDto getConfigList(int index);
  /**
   * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
   */
  int getConfigListCount();
  /**
   * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
   */
  java.util.List<? extends io.panshi.config.srv.ConfigDtoOrBuilder> 
      getConfigListOrBuilderList();
  /**
   * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
   */
  io.panshi.config.srv.ConfigDtoOrBuilder getConfigListOrBuilder(
      int index);
}
