// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConfigSrvDto.proto

package io.panshi.config.srv;

/**
 * Protobuf type {@code io.panshi.config.RegisterServiceInstanceResponse}
 */
public  final class RegisterServiceInstanceResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:io.panshi.config.RegisterServiceInstanceResponse)
    RegisterServiceInstanceResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RegisterServiceInstanceResponse.newBuilder() to construct.
  private RegisterServiceInstanceResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RegisterServiceInstanceResponse() {
    group_ = "";
    set_ = "";
    configList_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RegisterServiceInstanceResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            group_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            set_ = s;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              configList_ = new java.util.ArrayList<io.panshi.config.srv.ConfigDto>();
              mutable_bitField0_ |= 0x00000004;
            }
            configList_.add(
                input.readMessage(io.panshi.config.srv.ConfigDto.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        configList_ = java.util.Collections.unmodifiableList(configList_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.panshi.config.srv.ConfigSrvDto.internal_static_io_panshi_config_RegisterServiceInstanceResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.panshi.config.srv.ConfigSrvDto.internal_static_io_panshi_config_RegisterServiceInstanceResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.panshi.config.srv.RegisterServiceInstanceResponse.class, io.panshi.config.srv.RegisterServiceInstanceResponse.Builder.class);
  }

  private int bitField0_;
  public static final int GROUP_FIELD_NUMBER = 1;
  private volatile java.lang.Object group_;
  /**
   * <code>string group = 1;</code>
   */
  public java.lang.String getGroup() {
    java.lang.Object ref = group_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      group_ = s;
      return s;
    }
  }
  /**
   * <code>string group = 1;</code>
   */
  public com.google.protobuf.ByteString
      getGroupBytes() {
    java.lang.Object ref = group_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      group_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SET_FIELD_NUMBER = 2;
  private volatile java.lang.Object set_;
  /**
   * <code>string set = 2;</code>
   */
  public java.lang.String getSet() {
    java.lang.Object ref = set_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      set_ = s;
      return s;
    }
  }
  /**
   * <code>string set = 2;</code>
   */
  public com.google.protobuf.ByteString
      getSetBytes() {
    java.lang.Object ref = set_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      set_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONFIGLIST_FIELD_NUMBER = 3;
  private java.util.List<io.panshi.config.srv.ConfigDto> configList_;
  /**
   * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
   */
  public java.util.List<io.panshi.config.srv.ConfigDto> getConfigListList() {
    return configList_;
  }
  /**
   * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
   */
  public java.util.List<? extends io.panshi.config.srv.ConfigDtoOrBuilder> 
      getConfigListOrBuilderList() {
    return configList_;
  }
  /**
   * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
   */
  public int getConfigListCount() {
    return configList_.size();
  }
  /**
   * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
   */
  public io.panshi.config.srv.ConfigDto getConfigList(int index) {
    return configList_.get(index);
  }
  /**
   * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
   */
  public io.panshi.config.srv.ConfigDtoOrBuilder getConfigListOrBuilder(
      int index) {
    return configList_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getGroupBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, group_);
    }
    if (!getSetBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, set_);
    }
    for (int i = 0; i < configList_.size(); i++) {
      output.writeMessage(3, configList_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getGroupBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, group_);
    }
    if (!getSetBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, set_);
    }
    for (int i = 0; i < configList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, configList_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.panshi.config.srv.RegisterServiceInstanceResponse)) {
      return super.equals(obj);
    }
    io.panshi.config.srv.RegisterServiceInstanceResponse other = (io.panshi.config.srv.RegisterServiceInstanceResponse) obj;

    boolean result = true;
    result = result && getGroup()
        .equals(other.getGroup());
    result = result && getSet()
        .equals(other.getSet());
    result = result && getConfigListList()
        .equals(other.getConfigListList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + GROUP_FIELD_NUMBER;
    hash = (53 * hash) + getGroup().hashCode();
    hash = (37 * hash) + SET_FIELD_NUMBER;
    hash = (53 * hash) + getSet().hashCode();
    if (getConfigListCount() > 0) {
      hash = (37 * hash) + CONFIGLIST_FIELD_NUMBER;
      hash = (53 * hash) + getConfigListList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.panshi.config.srv.RegisterServiceInstanceResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.panshi.config.srv.RegisterServiceInstanceResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.panshi.config.srv.RegisterServiceInstanceResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.panshi.config.srv.RegisterServiceInstanceResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.panshi.config.srv.RegisterServiceInstanceResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.panshi.config.srv.RegisterServiceInstanceResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.panshi.config.srv.RegisterServiceInstanceResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.panshi.config.srv.RegisterServiceInstanceResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.panshi.config.srv.RegisterServiceInstanceResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.panshi.config.srv.RegisterServiceInstanceResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.panshi.config.srv.RegisterServiceInstanceResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.panshi.config.srv.RegisterServiceInstanceResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.panshi.config.srv.RegisterServiceInstanceResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code io.panshi.config.RegisterServiceInstanceResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.panshi.config.RegisterServiceInstanceResponse)
      io.panshi.config.srv.RegisterServiceInstanceResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.panshi.config.srv.ConfigSrvDto.internal_static_io_panshi_config_RegisterServiceInstanceResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.panshi.config.srv.ConfigSrvDto.internal_static_io_panshi_config_RegisterServiceInstanceResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.panshi.config.srv.RegisterServiceInstanceResponse.class, io.panshi.config.srv.RegisterServiceInstanceResponse.Builder.class);
    }

    // Construct using io.panshi.config.srv.RegisterServiceInstanceResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getConfigListFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      group_ = "";

      set_ = "";

      if (configListBuilder_ == null) {
        configList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        configListBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.panshi.config.srv.ConfigSrvDto.internal_static_io_panshi_config_RegisterServiceInstanceResponse_descriptor;
    }

    @java.lang.Override
    public io.panshi.config.srv.RegisterServiceInstanceResponse getDefaultInstanceForType() {
      return io.panshi.config.srv.RegisterServiceInstanceResponse.getDefaultInstance();
    }

    @java.lang.Override
    public io.panshi.config.srv.RegisterServiceInstanceResponse build() {
      io.panshi.config.srv.RegisterServiceInstanceResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.panshi.config.srv.RegisterServiceInstanceResponse buildPartial() {
      io.panshi.config.srv.RegisterServiceInstanceResponse result = new io.panshi.config.srv.RegisterServiceInstanceResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.group_ = group_;
      result.set_ = set_;
      if (configListBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          configList_ = java.util.Collections.unmodifiableList(configList_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.configList_ = configList_;
      } else {
        result.configList_ = configListBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.panshi.config.srv.RegisterServiceInstanceResponse) {
        return mergeFrom((io.panshi.config.srv.RegisterServiceInstanceResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.panshi.config.srv.RegisterServiceInstanceResponse other) {
      if (other == io.panshi.config.srv.RegisterServiceInstanceResponse.getDefaultInstance()) return this;
      if (!other.getGroup().isEmpty()) {
        group_ = other.group_;
        onChanged();
      }
      if (!other.getSet().isEmpty()) {
        set_ = other.set_;
        onChanged();
      }
      if (configListBuilder_ == null) {
        if (!other.configList_.isEmpty()) {
          if (configList_.isEmpty()) {
            configList_ = other.configList_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureConfigListIsMutable();
            configList_.addAll(other.configList_);
          }
          onChanged();
        }
      } else {
        if (!other.configList_.isEmpty()) {
          if (configListBuilder_.isEmpty()) {
            configListBuilder_.dispose();
            configListBuilder_ = null;
            configList_ = other.configList_;
            bitField0_ = (bitField0_ & ~0x00000004);
            configListBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getConfigListFieldBuilder() : null;
          } else {
            configListBuilder_.addAllMessages(other.configList_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.panshi.config.srv.RegisterServiceInstanceResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.panshi.config.srv.RegisterServiceInstanceResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object group_ = "";
    /**
     * <code>string group = 1;</code>
     */
    public java.lang.String getGroup() {
      java.lang.Object ref = group_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        group_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string group = 1;</code>
     */
    public com.google.protobuf.ByteString
        getGroupBytes() {
      java.lang.Object ref = group_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        group_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string group = 1;</code>
     */
    public Builder setGroup(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      group_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string group = 1;</code>
     */
    public Builder clearGroup() {
      
      group_ = getDefaultInstance().getGroup();
      onChanged();
      return this;
    }
    /**
     * <code>string group = 1;</code>
     */
    public Builder setGroupBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      group_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object set_ = "";
    /**
     * <code>string set = 2;</code>
     */
    public java.lang.String getSet() {
      java.lang.Object ref = set_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        set_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string set = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSetBytes() {
      java.lang.Object ref = set_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        set_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string set = 2;</code>
     */
    public Builder setSet(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      set_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string set = 2;</code>
     */
    public Builder clearSet() {
      
      set_ = getDefaultInstance().getSet();
      onChanged();
      return this;
    }
    /**
     * <code>string set = 2;</code>
     */
    public Builder setSetBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      set_ = value;
      onChanged();
      return this;
    }

    private java.util.List<io.panshi.config.srv.ConfigDto> configList_ =
      java.util.Collections.emptyList();
    private void ensureConfigListIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        configList_ = new java.util.ArrayList<io.panshi.config.srv.ConfigDto>(configList_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.panshi.config.srv.ConfigDto, io.panshi.config.srv.ConfigDto.Builder, io.panshi.config.srv.ConfigDtoOrBuilder> configListBuilder_;

    /**
     * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
     */
    public java.util.List<io.panshi.config.srv.ConfigDto> getConfigListList() {
      if (configListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(configList_);
      } else {
        return configListBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
     */
    public int getConfigListCount() {
      if (configListBuilder_ == null) {
        return configList_.size();
      } else {
        return configListBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
     */
    public io.panshi.config.srv.ConfigDto getConfigList(int index) {
      if (configListBuilder_ == null) {
        return configList_.get(index);
      } else {
        return configListBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
     */
    public Builder setConfigList(
        int index, io.panshi.config.srv.ConfigDto value) {
      if (configListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureConfigListIsMutable();
        configList_.set(index, value);
        onChanged();
      } else {
        configListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
     */
    public Builder setConfigList(
        int index, io.panshi.config.srv.ConfigDto.Builder builderForValue) {
      if (configListBuilder_ == null) {
        ensureConfigListIsMutable();
        configList_.set(index, builderForValue.build());
        onChanged();
      } else {
        configListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
     */
    public Builder addConfigList(io.panshi.config.srv.ConfigDto value) {
      if (configListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureConfigListIsMutable();
        configList_.add(value);
        onChanged();
      } else {
        configListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
     */
    public Builder addConfigList(
        int index, io.panshi.config.srv.ConfigDto value) {
      if (configListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureConfigListIsMutable();
        configList_.add(index, value);
        onChanged();
      } else {
        configListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
     */
    public Builder addConfigList(
        io.panshi.config.srv.ConfigDto.Builder builderForValue) {
      if (configListBuilder_ == null) {
        ensureConfigListIsMutable();
        configList_.add(builderForValue.build());
        onChanged();
      } else {
        configListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
     */
    public Builder addConfigList(
        int index, io.panshi.config.srv.ConfigDto.Builder builderForValue) {
      if (configListBuilder_ == null) {
        ensureConfigListIsMutable();
        configList_.add(index, builderForValue.build());
        onChanged();
      } else {
        configListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
     */
    public Builder addAllConfigList(
        java.lang.Iterable<? extends io.panshi.config.srv.ConfigDto> values) {
      if (configListBuilder_ == null) {
        ensureConfigListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, configList_);
        onChanged();
      } else {
        configListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
     */
    public Builder clearConfigList() {
      if (configListBuilder_ == null) {
        configList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        configListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
     */
    public Builder removeConfigList(int index) {
      if (configListBuilder_ == null) {
        ensureConfigListIsMutable();
        configList_.remove(index);
        onChanged();
      } else {
        configListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
     */
    public io.panshi.config.srv.ConfigDto.Builder getConfigListBuilder(
        int index) {
      return getConfigListFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
     */
    public io.panshi.config.srv.ConfigDtoOrBuilder getConfigListOrBuilder(
        int index) {
      if (configListBuilder_ == null) {
        return configList_.get(index);  } else {
        return configListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
     */
    public java.util.List<? extends io.panshi.config.srv.ConfigDtoOrBuilder> 
         getConfigListOrBuilderList() {
      if (configListBuilder_ != null) {
        return configListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(configList_);
      }
    }
    /**
     * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
     */
    public io.panshi.config.srv.ConfigDto.Builder addConfigListBuilder() {
      return getConfigListFieldBuilder().addBuilder(
          io.panshi.config.srv.ConfigDto.getDefaultInstance());
    }
    /**
     * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
     */
    public io.panshi.config.srv.ConfigDto.Builder addConfigListBuilder(
        int index) {
      return getConfigListFieldBuilder().addBuilder(
          index, io.panshi.config.srv.ConfigDto.getDefaultInstance());
    }
    /**
     * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
     */
    public java.util.List<io.panshi.config.srv.ConfigDto.Builder> 
         getConfigListBuilderList() {
      return getConfigListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.panshi.config.srv.ConfigDto, io.panshi.config.srv.ConfigDto.Builder, io.panshi.config.srv.ConfigDtoOrBuilder> 
        getConfigListFieldBuilder() {
      if (configListBuilder_ == null) {
        configListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.panshi.config.srv.ConfigDto, io.panshi.config.srv.ConfigDto.Builder, io.panshi.config.srv.ConfigDtoOrBuilder>(
                configList_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        configList_ = null;
      }
      return configListBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:io.panshi.config.RegisterServiceInstanceResponse)
  }

  // @@protoc_insertion_point(class_scope:io.panshi.config.RegisterServiceInstanceResponse)
  private static final io.panshi.config.srv.RegisterServiceInstanceResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.panshi.config.srv.RegisterServiceInstanceResponse();
  }

  public static io.panshi.config.srv.RegisterServiceInstanceResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RegisterServiceInstanceResponse>
      PARSER = new com.google.protobuf.AbstractParser<RegisterServiceInstanceResponse>() {
    @java.lang.Override
    public RegisterServiceInstanceResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RegisterServiceInstanceResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RegisterServiceInstanceResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RegisterServiceInstanceResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.panshi.config.srv.RegisterServiceInstanceResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

