// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConfigSrv.proto

package io.panshi.config.srv;

public final class ConfigSrvOuterClass {
  private ConfigSrvOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017ConfigSrv.proto\022\020io.panshi.config\032\022Con" +
      "figSrvDto.proto2\264\002\n\tConfigSrv\022]\n\014createC" +
      "onfig\022%.io.panshi.config.CreateConfigReq" +
      "uest\032&.io.panshi.config.CreateConfigResp" +
      "onse\022o\n\026registerClientInstance\022).io.pans" +
      "hi.config.RegisterInstanceRequest\032*.io.p" +
      "anshi.config.RegisterInstanceResponse\022W\n" +
      "\nlistConfig\022#.io.panshi.config.ListConfi" +
      "gRequest\032$.io.panshi.config.ListConfigRe" +
      "sponseB\030\n\024io.panshi.config.srvP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.panshi.config.srv.ConfigSrvDto.getDescriptor(),
        }, assigner);
    io.panshi.config.srv.ConfigSrvDto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
