// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConfigSrvDto.proto

package io.panshi.config.srv;

public final class ConfigSrvDto {
  private ConfigSrvDto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_panshi_config_ConfigDto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_panshi_config_ConfigDto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_panshi_config_CreateConfigRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_panshi_config_CreateConfigRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_panshi_config_CreateConfigResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_panshi_config_CreateConfigResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_panshi_config_RegisterInstanceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_panshi_config_RegisterInstanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_panshi_config_RegisterInstanceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_panshi_config_RegisterInstanceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_panshi_config_ListConfigRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_panshi_config_ListConfigRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_panshi_config_ListConfigResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_panshi_config_ListConfigResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022ConfigSrvDto.proto\022\020io.panshi.config\032\025" +
      "ConfigSrvCommon.proto\"o\n\tConfigDto\022\r\n\005gr" +
      "oup\030\001 \001(\t\022\013\n\003set\030\002 \001(\t\022\013\n\003key\030\003 \001(\t\022\027\n\017c" +
      "onfigValueType\030\004 \001(\t\022\017\n\007content\030\005 \001(\t\022\017\n" +
      "\007version\030\006 \001(\003\"d\n\023CreateConfigRequest\022\013\n" +
      "\003key\030\001 \001(\t\022\r\n\005group\030\002 \001(\t\022\013\n\003set\030\003 \001(\t\022\017" +
      "\n\007content\030\004 \001(\t\022\023\n\013contentType\030\005 \001(\t\"R\n\024" +
      "CreateConfigResponse\022.\n\004cRsp\030\001 \001(\0132 .io." +
      "panshi.config.CommonResponse\022\n\n\002id\030\002 \001(\t" +
      "\"H\n\027RegisterInstanceRequest\022\r\n\005group\030\001 \001" +
      "(\t\022\013\n\003set\030\002 \001(\t\022\021\n\tipAddress\030\003 \001(\t\"g\n\030Re" +
      "gisterInstanceResponse\022\r\n\005group\030\001 \001(\t\022\013\n" +
      "\003set\030\002 \001(\t\022/\n\nconfigList\030\003 \003(\0132\033.io.pans" +
      "hi.config.ConfigDto\"G\n\021ListConfigRequest" +
      "\022\r\n\005group\030\001 \001(\t\022\013\n\003set\030\002 \001(\t\022\026\n\016currentV" +
      "ersion\030\003 \001(\t\"\212\001\n\022ListConfigResponse\022.\n\004c" +
      "Rsp\030\001 \001(\0132 .io.panshi.config.CommonRespo" +
      "nse\022\023\n\013lastVersion\030\002 \001(\003\022/\n\nconfigList\030\003" +
      " \003(\0132\033.io.panshi.config.ConfigDtoB\030\n\024io." +
      "panshi.config.srvP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.panshi.config.srv.ConfigSrvCommon.getDescriptor(),
        }, assigner);
    internal_static_io_panshi_config_ConfigDto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_panshi_config_ConfigDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_panshi_config_ConfigDto_descriptor,
        new java.lang.String[] { "Group", "Set", "Key", "ConfigValueType", "Content", "Version", });
    internal_static_io_panshi_config_CreateConfigRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_io_panshi_config_CreateConfigRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_panshi_config_CreateConfigRequest_descriptor,
        new java.lang.String[] { "Key", "Group", "Set", "Content", "ContentType", });
    internal_static_io_panshi_config_CreateConfigResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_io_panshi_config_CreateConfigResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_panshi_config_CreateConfigResponse_descriptor,
        new java.lang.String[] { "CRsp", "Id", });
    internal_static_io_panshi_config_RegisterInstanceRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_io_panshi_config_RegisterInstanceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_panshi_config_RegisterInstanceRequest_descriptor,
        new java.lang.String[] { "Group", "Set", "IpAddress", });
    internal_static_io_panshi_config_RegisterInstanceResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_io_panshi_config_RegisterInstanceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_panshi_config_RegisterInstanceResponse_descriptor,
        new java.lang.String[] { "Group", "Set", "ConfigList", });
    internal_static_io_panshi_config_ListConfigRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_io_panshi_config_ListConfigRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_panshi_config_ListConfigRequest_descriptor,
        new java.lang.String[] { "Group", "Set", "CurrentVersion", });
    internal_static_io_panshi_config_ListConfigResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_io_panshi_config_ListConfigResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_panshi_config_ListConfigResponse_descriptor,
        new java.lang.String[] { "CRsp", "LastVersion", "ConfigList", });
    io.panshi.config.srv.ConfigSrvCommon.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
