// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConfigSrvDto.proto

package io.panshi.config.srv;

public interface RegisterServiceInstanceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.panshi.config.RegisterServiceInstanceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string group = 1;</code>
   */
  java.lang.String getGroup();
  /**
   * <code>string group = 1;</code>
   */
  com.google.protobuf.ByteString
      getGroupBytes();

  /**
   * <code>string set = 2;</code>
   */
  java.lang.String getSet();
  /**
   * <code>string set = 2;</code>
   */
  com.google.protobuf.ByteString
      getSetBytes();

  /**
   * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
   */
  java.util.List<io.panshi.config.srv.ConfigDto> 
      getConfigListList();
  /**
   * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
   */
  io.panshi.config.srv.ConfigDto getConfigList(int index);
  /**
   * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
   */
  int getConfigListCount();
  /**
   * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
   */
  java.util.List<? extends io.panshi.config.srv.ConfigDtoOrBuilder> 
      getConfigListOrBuilderList();
  /**
   * <code>repeated .io.panshi.config.ConfigDto configList = 3;</code>
   */
  io.panshi.config.srv.ConfigDtoOrBuilder getConfigListOrBuilder(
      int index);
}
