// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConfigSrvDto.proto

package io.panshi.config.srv;

public interface RegisterServiceInstanceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.panshi.config.RegisterServiceInstanceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string group = 1;</code>
   */
  java.lang.String getGroup();
  /**
   * <code>string group = 1;</code>
   */
  com.google.protobuf.ByteString
      getGroupBytes();

  /**
   * <code>string set = 2;</code>
   */
  java.lang.String getSet();
  /**
   * <code>string set = 2;</code>
   */
  com.google.protobuf.ByteString
      getSetBytes();

  /**
   * <code>string ipAddress = 3;</code>
   */
  java.lang.String getIpAddress();
  /**
   * <code>string ipAddress = 3;</code>
   */
  com.google.protobuf.ByteString
      getIpAddressBytes();
}
